export const GET_MOVIES = 'GET_MOVIES';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const SET_FILTERS_CATEGORIES = 'SET_FILTERS_CATEGORIES';
export const TOGGLE_CATEGORY_STATE = 'TOGGLE_CATEGORY_STATE';
export const EVOLUATE_MOVIE = 'EVOLUATE_MOVIE';
export const FILTER_MOVIES = 'FILTER_MOVIES';
